version: '3.8'

services:
  db:
    build:
      context: ./mysql        # 指向子目录
      dockerfile: Dockerfile
      # 如果 MySQL 的 Dockerfile 需要构建参数，可以在这里添加
      args:
        - DB_NAME=${DB_NAME}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    container_name: screw_out-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      # 冒号前面是物理机的目录，后面是容器内目录
      - /var/lib/screw_out/mysql:/var/lib/mysql
    environment:
      # 从 .env 文件自动读取变量
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  api:
    build:
      # context 表示去哪里找 *.dockerfile
      context: ./nestjs-app   # 指向子目录，这样它会读取 ./nestjs-app/.dockerignore
      dockerfile: Dockerfile
    container_name: screw_out-nestjs
    restart: always
    ports:
      - "${APP_PORT}:3000"
    volumes:
      # 冒号前面是物理机的目录，后面是容器内目录
      - /home/ubuntu/Projects/ScrewOut-backend/nestjs-app/certs:/app/certs:ro # 将宿主机证书文件夹挂载到容器内
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    healthcheck:
      # 使用 netcat 命令检查容器内的 3000 端口是否可以被访问
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 10s       # 每 10 秒检查一次
      timeout: 5s         # 每次检查的超时时间
      retries: 5          # 连续 5 次失败后，才将容器标记为 unhealthy
      start_period: 10s   # 容器启动后，等待 10 秒再开始第一次健康检查

  nginx:
    image: docker.m.daocloud.io/library/nginx:latest # <-- 换成这一行
    container_name: screw_out-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 冒号前面是物理机的目录，后面是容器内目录
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/Projects/ScrewOut-backend/nestjs-app/certs:/etc/nginx/certs:ro
    depends_on:
      # 不仅等待 api 启动，还要等待它达到健康状态
      api:
        condition: service_healthy
