version: '3.8'

services:
  db:
    build:
      context: ./mysql        # 指向子目录
      dockerfile: Dockerfile
      # 如果 MySQL 的 Dockerfile 需要构建参数，可以在这里添加
      args:
        - DB_NAME=${DB_NAME}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    container_name: screw_out-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      # 冒号前面是物理机的目录，后面是容器内目录
      - /var/lib/screw_out/mysql:/var/lib/mysql
    environment:
      # 从 .env 文件自动读取变量
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  api:
    build:
      # context 表示去哪里找 *.dockerfile
      context: ./nestjs-app   # 指向子目录，这样它会读取 ./nestjs-app/.dockerignore
      dockerfile: Dockerfile
    container_name: screw_out-nestjs
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      # 冒号前面是物理机的目录，后面是容器内目录
      - /home/ubuntu/Projects/ScrewOut-backend/nestjs-app/certs:/app/certs:ro # 将宿主机证书文件夹挂载到容器内
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}